// ============================================================
// Mock fallback data — used when the real API is unavailable
// ============================================================

import type {
  CallAgentResponse,
  VoiceOption,
  NumberInfo,
  TaskAgentResponse,
  CampaignResponse,
  AudienceResponse,
  DashboardDailyCallsResponse,
  PaginatedCallInsightsResponse,
} from '@/types/api';

export const mockAgents: CallAgentResponse[] = [
  {
    id: 1,
    prompt: { system: 'You are a professional sales qualification agent.' },
    agent_name: 'Sales Qualifier',
    agent_phone_number: '+1234567890',
    voice_id: 'v-sarah',
    version: 1,
    welcome_text: { default: 'Hi, this is Sarah from TechCorp. Am I speaking with {{name}}?' },
    tools: null,
    enabled: true,
    save_stats: true,
    server_type: 'PROD',
    call_type: 'OUTGOING',
    created_at: '2024-12-01T10:00:00Z',
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    user_persona: null,
    client_id: null,
    pair_agent_id: null,
    health_monitoring_enabled: false,
    health_alert_emails: null,
    last_health_status: null,
    last_health_checked_at: null,
  },
  {
    id: 2,
    prompt: { system: 'You are a helpful customer support agent.' },
    agent_name: 'Customer Support',
    agent_phone_number: '+1234567891',
    voice_id: 'v-james',
    version: 1,
    welcome_text: { default: 'Thank you for calling. How can I help you today?' },
    tools: null,
    enabled: true,
    save_stats: true,
    server_type: 'PROD',
    call_type: 'INCOMING',
    created_at: '2024-12-05T10:00:00Z',
    updated_at: new Date(Date.now() - 1800000).toISOString(),
    user_persona: null,
    client_id: null,
    pair_agent_id: null,
    health_monitoring_enabled: true,
    health_alert_emails: null,
    last_health_status: 'healthy',
    last_health_checked_at: new Date().toISOString(),
  },
  {
    id: 3,
    prompt: { system: 'Schedule appointments with qualified prospects.' },
    agent_name: 'Appointment Setter',
    agent_phone_number: '+1234567892',
    voice_id: 'v-michael',
    version: 1,
    welcome_text: { default: 'Hello {{name}}, I\'m calling to schedule your consultation.' },
    tools: null,
    enabled: true,
    save_stats: true,
    server_type: 'PROD',
    call_type: 'OUTGOING',
    created_at: '2024-12-10T10:00:00Z',
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    user_persona: null,
    client_id: null,
    pair_agent_id: null,
    health_monitoring_enabled: false,
    health_alert_emails: null,
    last_health_status: null,
    last_health_checked_at: null,
  },
  {
    id: 4,
    prompt: { system: 'Conduct customer satisfaction surveys.' },
    agent_name: 'Survey Bot',
    agent_phone_number: '+1234567893',
    voice_id: 'v-priya',
    version: 1,
    welcome_text: { default: 'Hi {{name}}, we would love to get your feedback.' },
    tools: null,
    enabled: false,
    save_stats: true,
    server_type: 'PROD',
    call_type: 'OUTGOING',
    created_at: '2024-11-20T10:00:00Z',
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    user_persona: null,
    client_id: null,
    pair_agent_id: null,
    health_monitoring_enabled: false,
    health_alert_emails: null,
    last_health_status: null,
    last_health_checked_at: null,
  },
  {
    id: 5,
    prompt: { system: 'Nurture warm leads with personalized follow-ups.' },
    agent_name: 'Lead Nurture',
    agent_phone_number: '+1234567894',
    voice_id: 'v-sarah',
    version: 1,
    welcome_text: { default: 'Hi {{name}}, following up on your interest in our services.' },
    tools: null,
    enabled: true,
    save_stats: true,
    server_type: 'PROD',
    call_type: 'OUTGOING',
    created_at: '2024-12-15T10:00:00Z',
    updated_at: new Date(Date.now() - 10800000).toISOString(),
    user_persona: null,
    client_id: null,
    pair_agent_id: null,
    health_monitoring_enabled: false,
    health_alert_emails: null,
    last_health_status: null,
    last_health_checked_at: null,
  },
  {
    id: 6,
    prompt: { system: 'Remind customers about pending payments professionally.' },
    agent_name: 'Payment Reminder',
    agent_phone_number: '+1234567895',
    voice_id: 'v-james',
    version: 1,
    welcome_text: { default: 'Hello {{name}}, this is a reminder about your upcoming payment.' },
    tools: null,
    enabled: true,
    save_stats: true,
    server_type: 'PROD',
    call_type: 'OUTGOING',
    created_at: '2024-12-18T10:00:00Z',
    updated_at: new Date(Date.now() - 2700000).toISOString(),
    user_persona: null,
    client_id: null,
    pair_agent_id: null,
    health_monitoring_enabled: false,
    health_alert_emails: null,
    last_health_status: null,
    last_health_checked_at: null,
  },
];

export const mockVoices: VoiceOption[] = [
  { voice_id: 'v-sarah', name: 'Sarah (American, Female)' },
  { voice_id: 'v-james', name: 'James (British, Male)' },
  { voice_id: 'v-priya', name: 'Priya (Indian, Female)' },
  { voice_id: 'v-michael', name: 'Michael (American, Male)' },
  { voice_id: 'v-emma', name: 'Emma (British, Female)' },
  { voice_id: 'v-alex', name: 'Alex (American, Neutral)' },
  { voice_id: 'v-raj', name: 'Raj (Indian, Male)' },
  { voice_id: 'v-sophie', name: 'Sophie (Australian, Female)' },
];

export const mockNumbers: NumberInfo[] = [
  { number: '+1234567890' },
  { number: '+1234567891' },
  { number: '+1234567892' },
];

export const mockTaskAgents: TaskAgentResponse[] = [
  {
    id: 1,
    prompt: { system: 'Analyze sales call and extract insights.' },
    task_details: null,
    agent_name: 'Sales Insight Agent',
    agent_task: 'INSIGHT_GENERATION',
    enabled: true,
    version: 1,
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-20T10:00:00Z',
    agent_id: 1,
  },
];

const now = new Date();
function daysAgo(n: number) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const mockCampaigns: CampaignResponse[] = [
  {
    campaign_id: 'camp-1',
    status: 'IN_PROGRESS',
    audience_id: 'aud-1',
    description: 'Q1 sales outreach',
    campaign_name: 'Q1 Outreach Campaign',
    size: 2450,
    created_at: daysAgo(15),
    updated_at: daysAgo(0),
    agent_id: 1,
    call_status_summary: { ANSWERED: 892, FAILED: 45, NOT_ANSWERED: 310, IN_PROGRESS: 0, QUEUED: 0, LINE_BUSY: 0 },
    post_call_actions: null,
    start_time: daysAgo(10),
    scheduled_start_time: daysAgo(10),
    paused_at: null,
    cancelled_at: null,
    file_url: null,
  },
  {
    campaign_id: 'camp-2',
    status: 'SCHEDULED',
    audience_id: 'aud-2',
    description: 'Payment reminders for February',
    campaign_name: 'Payment Reminders Feb',
    size: 234,
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    agent_id: 6,
    call_status_summary: null,
    post_call_actions: null,
    start_time: null,
    scheduled_start_time: new Date(now.getTime() + 86400000 * 3).toISOString(),
    paused_at: null,
    cancelled_at: null,
    file_url: null,
  },
  {
    campaign_id: 'camp-3',
    status: 'COMPLETED',
    audience_id: 'aud-3',
    description: 'Follow up webinar attendees',
    campaign_name: 'Webinar Follow-up',
    size: 1234,
    created_at: daysAgo(30),
    updated_at: daysAgo(20),
    agent_id: 5,
    call_status_summary: { ANSWERED: 987, FAILED: 12, NOT_ANSWERED: 235, IN_PROGRESS: 0, QUEUED: 0, LINE_BUSY: 0 },
    post_call_actions: null,
    start_time: daysAgo(28),
    scheduled_start_time: daysAgo(28),
    paused_at: null,
    cancelled_at: null,
    file_url: null,
  },
  {
    campaign_id: 'camp-4',
    status: 'DRAFTED',
    audience_id: 'aud-4',
    description: 'Enterprise demo calls',
    campaign_name: 'Enterprise Demo Calls',
    size: 89,
    created_at: daysAgo(2),
    updated_at: daysAgo(0),
    agent_id: 3,
    call_status_summary: null,
    post_call_actions: null,
    start_time: null,
    scheduled_start_time: null,
    paused_at: null,
    cancelled_at: null,
    file_url: null,
  },
];

export const mockAudiences: AudienceResponse[] = [
  { id: 'aud-1', name: 'Q1 Sales Leads', description: 'Leads from Q1 campaigns', file_url: 'file.csv', is_processed: true, created_at: daysAgo(20), updated_at: daysAgo(2), size: 2450 },
  { id: 'aud-2', name: 'Payment Due', description: 'Customers with pending payments', file_url: 'payments.csv', is_processed: true, created_at: daysAgo(10), updated_at: daysAgo(5), size: 234 },
  { id: 'aud-3', name: 'Webinar Attendees', description: null, file_url: 'webinar.csv', is_processed: true, created_at: daysAgo(35), updated_at: daysAgo(30), size: 1234 },
  { id: 'aud-4', name: 'Enterprise Prospects', description: 'High-value enterprise leads', file_url: null, is_processed: true, created_at: daysAgo(5), updated_at: daysAgo(2), size: 89 },
];

export const mockDashboardDailyCalls: DashboardDailyCallsResponse = {
  summary: {
    total_calls: 487,
    from_date: daysAgo(7).split('T')[0],
    to_date: daysAgo(0).split('T')[0],
  },
  daily: Array.from({ length: 7 }, (_, i) => {
    const total = Math.floor(Math.random() * 120) + 30;
    const answered = Math.floor(total * (0.55 + Math.random() * 0.25));
    return {
      date: daysAgo(6 - i).split('T')[0],
      total_calls: total,
      answered_calls: answered,
      failed_calls: total - answered,
    };
  }),
};

export const mockCallInsights: PaginatedCallInsightsResponse = {
  meta: { total: 5, has_next: false },
  data: [
    {
      id: 1, call_id: 'call-001', agent_id: 1, insights_data: { interest_level: 'High' },
      call_audit: null, call_quality: null, call_context: null,
      call_disposition: 'Interested', call_summary: 'Prospect showed strong interest in the product.',
      is_verified: true, verified_by: null, verification_history: [],
      created_at: daysAgo(1), updated_at: daysAgo(1),
      call_duration: 245, recording_url: null, transcript_url: null,
      call_transcription: [
        { role: 'Agent', content: 'Hi, this is Sarah from TechCorp.' },
        { role: 'User', content: 'Yes, I am interested in your product.' },
      ],
      call_timeline: null, from_number: '+1234567890', to_number: '+9876543210',
      direction: 'outbound', user_number: '+9876543210',
    },
    {
      id: 2, call_id: 'call-002', agent_id: 2, insights_data: { issue_type: 'Billing' },
      call_audit: null, call_quality: null, call_context: null,
      call_disposition: 'Issue Resolved', call_summary: 'Customer billing issue resolved.',
      is_verified: false, verified_by: null, verification_history: [],
      created_at: daysAgo(1), updated_at: daysAgo(1),
      call_duration: 180, recording_url: null, transcript_url: null,
      call_transcription: [
        { role: 'Agent', content: 'Thank you for calling support.' },
        { role: 'User', content: 'I have a billing question.' },
      ],
      call_timeline: null, from_number: '+9876543211', to_number: '+1234567891',
      direction: 'inbound', user_number: '+9876543211',
    },
    {
      id: 3, call_id: 'call-003', agent_id: 3, insights_data: { appointment_set: true },
      call_audit: null, call_quality: null, call_context: null,
      call_disposition: 'Appointment Set', call_summary: 'Demo scheduled for next week.',
      is_verified: true, verified_by: null, verification_history: [],
      created_at: daysAgo(2), updated_at: daysAgo(2),
      call_duration: 312, recording_url: null, transcript_url: null,
      call_transcription: [],
      call_timeline: null, from_number: '+1234567892', to_number: '+9876543212',
      direction: 'outbound', user_number: '+9876543212',
    },
    {
      id: 4, call_id: 'call-004', agent_id: 1, insights_data: null,
      call_audit: null, call_quality: null, call_context: null,
      call_disposition: 'Not Interested', call_summary: null,
      is_verified: false, verified_by: null, verification_history: [],
      created_at: daysAgo(3), updated_at: daysAgo(3),
      call_duration: 0, recording_url: null, transcript_url: null,
      call_transcription: [],
      call_timeline: null, from_number: '+1234567890', to_number: '+9876543213',
      direction: 'outbound', user_number: '+9876543213',
    },
    {
      id: 5, call_id: 'call-005', agent_id: 5, insights_data: { interest_level: 'Medium' },
      call_audit: null, call_quality: null, call_context: null,
      call_disposition: 'Callback Requested', call_summary: 'Lead asked for a callback next week.',
      is_verified: false, verified_by: null, verification_history: [],
      created_at: daysAgo(0), updated_at: daysAgo(0),
      call_duration: 156, recording_url: null, transcript_url: null,
      call_transcription: [
        { role: 'Agent', content: 'Following up on your interest.' },
        { role: 'User', content: 'Can you call me next week?' },
      ],
      call_timeline: null, from_number: '+1234567894', to_number: '+9876543214',
      direction: 'outbound', user_number: '+9876543214',
    },
  ],
};
